export default Object.freeze({
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOTFOUND: 'NOTFOUND',
  USER_NOTFOUND: 'USER_NOTFOUND',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
});
